### ISSUE TITLE
Invalid/Expired WorkFlow Signature

### ISSUE THREAD

**Issue by atellier** [cronicle-edge/cronicle-edge#30]
Hello,

I am randomly getting "Error: Invalid/Expired WorkFlow Signature" failures. They happen randomly, and these events are part of a chain of events (mostly workflows that trigger some other workflows in a chain). This error would happen on different events so it is not one in particular. I would love to provide more info, but this happens randomly (I would say 1% of the time) and logs show no more info than that.

How would I go about helping troubleshooting that error?

Thank you,

**Comment by mikeTWC1984** [comment]
Are you using latest version? There was similar issue few releases before

Regarding empty WF -  it's treaded as error by design. We can add an option to allow empty WF. For now keep using dummy event, or tweak that plugin yourself - all you need is just add the line checking if task list is empty and if so exit with code 0.

**Comment by mikeTWC1984** [comment]
Yeah, if yo are on 1.5.8 upgrade won't help. OK, I'll do some research. Can you copy here output of console for the failed job?
You mentioned this happens on WF that is chaining another WF? Or this affect standalone WF too? Will try to recreate.

Also, do you have multiple nodes in the cluster or just 1? If so, try to force WF event to run on master node.

**Comment by mikeTWC1984** [comment]
I was able to reproduce. I chained 2 workflows and one of the execution returned this error. Will try to fix asap

**Comment by atellier** [comment]
> I was able to reproduce. I chained 2 workflows and one of the execution returned this error. Will try to fix asap

Great news - thank you very much for your support!

**Comment by mikeTWC1984** [comment]
Sorry for delay. I believe the root cause is that job is calling rest api to invoke jobs earlier then temp api key is generated/stored (probably when disk gets slow or something like that).  As a "duck tape" solution you my try add optional extra lag for initial  api call.

Since it's hard to reproduce this issue, I might need your assistance  in testing this:

- Locate this line in workflow plugin file (bin/workflow.js):
https://github.com/cronicle-edge/cronicle-edge/blob/main/bin/workflow.js#L102

- replace it with below snippet
```js
		let sched;
		try {
			sched = await getJson(baseUrl + '/api/app/get_schedule') 
		}
		catch {
			console.log("failed to fetch scheduled jobs, retrying...")
			await sleep(300);
			sched = await getJson(baseUrl + '/api/app/get_schedule')		    	
		}
```

Hopefully issue will go away after that. This is temp solution, I will try to figure out something better on the next release.
Regarding empty workflow - use some placeholder job for now.

**Comment by mikeTWC1984** [comment]
OK, try to increase delay to 1000 or so. If it won't help likely we need to dig deeper.

Out of curiosity, where do you run your manager node (phisical/vm/ec2)? what are os/cpu/ram/node version etc?

**Comment by mikeTWC1984** [comment]
Also let's print error message. Maybe it's just timeout due to network issues

```js
		let sched;
		try {
			sched = await getJson(baseUrl + '/api/app/get_schedule') 
		}
		catch (e) {
			console.log("failed to fetch scheduled jobs, retrying...")
                        console.log("error details:", e);
			await sleep(300);
			sched = await getJson(baseUrl + '/api/app/get_schedule')		    	
		}
```

**Comment by mikeTWC1984** [comment]
I think I see how can this be fixed. More over - if you run WF job on worker node it will likely fix the problem too.
I'll do some experiments and update the code

**Comment by mikeTWC1984** [comment]
Ok, hopefully this should be fixed on 1.5.11

**Comment by atellier** [comment]
Hello

We have been the new version (1.5.14) for a few days, and unfortunately we still see these errors. We have two environments, one where we have only one server (and we do not see the error - all is fine), and another one where we have two workers (and we do see the issue there, even though fairly rarely). So it appears that the issue is still present when we have more than one worker nodes.

Machines are 8CPU 16GB mem and are within 1ms latency of each other. Please let me know if I can help further troubleshoot.

Thanks!

**Comment by mikeTWC1984** [comment]
OK, thanks for reporting this. I guess we'd need to switch back to generating temp keys for workflows. Will do it on the next release.

**Comment by mikeTWC1984** [comment]
OK, hopefully this is fixed on the new release (1.5.15).
